name: eval14c
dependencies:
    - python=3.11
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - cartopy
    - pandas
    - openpyxl # read .xlsx files
    - xarray
    - dask # to open multiple files at once with xarray
    - h5py
    - netcdf4
    - numba # for just-in-time compilation
    - tqdm # progress bar
    - loguru
    - py7zr # for 7z archives
    - pip
    - pip:
        - soilgrids
        - rioxarray # read geotiff files
        - f90nml # to edit fortran namelist files
        - -e . # editable installation of evaluate-SOC-models using setup.py

    # Dependencies of the SOMic model's R package:
    - r-base=4.2
    - r-devtools
    - r-recommended
    - r-ggplot2
    - r-data.table
